#if !canImport(ObjectiveC)
import XCTest

extension FluentSQLiteDriverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentSQLiteDriverTests = [
        ("testAggregates", testAggregates),
        ("testAll", testAll),
        ("testAsyncCreate", testAsyncCreate),
        ("testBatchCreate", testBatchCreate),
        ("testBatchUpdate", testBatchUpdate),
        ("testChunkedFetch", testChunkedFetch),
        ("testCreate", testCreate),
        ("testDelete", testDelete),
        ("testEagerLoadChildren", testEagerLoadChildren),
        ("testEagerLoadJSON", testEagerLoadJSON),
        ("testEagerLoadParent", testEagerLoadParent),
        ("testEagerLoadParentJoin", testEagerLoadParentJoin),
        ("testIdentifierGeneration", testIdentifierGeneration),
        ("testJoin", testJoin),
        ("testMigrator", testMigrator),
        ("testMigratorError", testMigratorError),
        ("testNestedModel", testNestedModel),
        ("testNullifyField", testNullifyField),
        ("testRead", testRead),
        ("testUniqueFields", testUniqueFields),
        ("testUpdate", testUpdate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentSQLiteDriverTests.__allTests__FluentSQLiteDriverTests),
    ]
}
#endif
