#if !canImport(ObjectiveC)
import XCTest

extension FluentSQLiteDriverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentSQLiteDriverTests = [
        ("testAggregates", testAggregates),
        ("testAll", testAll),
        ("testAsyncCreate", testAsyncCreate),
        ("testBatchCreate", testBatchCreate),
        ("testBatchUpdate", testBatchUpdate),
        ("testChunkedFetch", testChunkedFetch),
        ("testCreate", testCreate),
        ("testDelete", testDelete),
        ("testEagerLoadChildren", testEagerLoadChildren),
        ("testEagerLoadChildrenJSON", testEagerLoadChildrenJSON),
        ("testEagerLoadParent", testEagerLoadParent),
        ("testEagerLoadParentJoin", testEagerLoadParentJoin),
        ("testEagerLoadParentJSON", testEagerLoadParentJSON),
        ("testFieldFilter", testFieldFilter),
        ("testIdentifierGeneration", testIdentifierGeneration),
        ("testJoin", testJoin),
        ("testJoinedFieldFilter", testJoinedFieldFilter),
        ("testMigrator", testMigrator),
        ("testMigratorError", testMigratorError),
        ("testModelMiddleware", testModelMiddleware),
        ("testMultipleJoinSameTable", testMultipleJoinSameTable),
        ("testNestedModel", testNestedModel),
        ("testNewModelDecode", testNewModelDecode),
        ("testNullifyField", testNullifyField),
        ("testOptionalParent", testOptionalParent),
        ("testRead", testRead),
        ("testSiblingsAttach", testSiblingsAttach),
        ("testSiblingsEagerLoad", testSiblingsEagerLoad),
        ("testSoftDelete", testSoftDelete),
        ("testSort", testSort),
        ("testTimestampable", testTimestampable),
        ("testUniqueFields", testUniqueFields),
        ("testUpdate", testUpdate),
        ("testUUIDModel", testUUIDModel),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentSQLiteDriverTests.__allTests__FluentSQLiteDriverTests),
    ]
}
#endif
